// var nouns = [
//     "snake",
//     "spartan",
//     "ass",
//     "duck",
//     "viking",
//     "vampire",
//     "vulture",
//     "tri-borg",
//     "Bunny",
//     "U.S.S Arizona",
//     "Aircraft Carrier",
//     "Retard",
//     "Grave Digger",
//     "Tom Cruise",
//     "Duracell Battery",
//     "Robo-cop",
//     "Terminator",
//     "Cyber Ninja",
//     "Ninja",
//     "Reptile",
//     "Lizard",
//     "General",
//     "Viltrumite",
//     "cat",
//     "tiger",
//     "lion",
//     "lemur",
//     "sorcerer",
//     "wizard",
//     "witch",
//     "robot",
//     "clorox wipe",
//     "zombie",
//     "hell-spawn",
//     "anti-christ",
//     "minion",
//     "jesus",
//     "god",
//     "titan",
//     "ogre",
//     "cyclops",
//     "centaur",
//     "satyr",
//     "necromancer",
//     "cyborg",
//     "demon",
//     "dragon",
//     "knight",
//     "damsel",
//     "woman",
//     "man",
//     "elemental",
//     "troll",
//     "experiment",
//     "immortal",
//     "outworlder",
//     "feminist",
//     "activist",
//     "politician",
//     "king",
//     "queen",
//     "kryptonian",
//     "super hero",
//     "xenomorph",
//     "alien",
//     "doll",
//     "spirit",
//     "ghost",
//     "killer",
//     "murderer",
//     "psychopath",
//     "banana",
//     "apple",
//     "grape",
//     "steak",
//     "coach",
//     "leader",
//     "dog-catcher",
//     "fire-fighter",
//     "actor",
//     "movie-star",
//     "janitor",
//     "plumber",
//     "urophiliac",
//     "European",
//     "Asian",
//     "weight lifter",
//     "power lifter",
//     "teddy bear",
//     "burn-victim",
//     "wrestler",
//     "penguin",
//     "octopus",
//     "pirate",
//     "monster",
//     "ballerina",
//     "elf",
//     "clown",
//     "pornstar",
//     "mistake",
//     "neutron star",
//     "ape",
//     "baby",
//     "terrorist",
//     "godzilla",
//     "donkey",
//     "platypus",
//     "warrior",
//     "soldier",
//     "assassin",
//     "accountant",
//     "cop",
//     "monk",
//     "genie",
//     "yoga instructor",
//     "hobbit",
//     "dwarf",
//     "lord",
//     "wolverine",
//     "star",
//     "dwarf star",
//     "black hole",
//     "goblin",
//     "furry",
//     "skeleton",
//     "jaeger",
//     "bachelor",
//     "master",
//     "panda",
//     "mercenary",
//     "agent",
//     "secret agent",
//     "chef",
//     "salesman",
//     "janitor",
//     "CEO",
//     "pilot",
//     "loser",
//     "Obama",
//     "guy",
//     "dead guy",
//     "half blood",
//     "gold fish",
//     "fish",
//     "sea monster",
//     "lochness monster",
//     "captain",
//     "wedding planner",
//     "mom",
//     "photographer",
//     "maniac",
//     "offspring",
//     "taste tester",
//     "hooker",
//     "construction worker",
//     "stripper",
//     "murder clown",
//     "teenager",
//     "old man",
//     "grandpa",
//     "grandma",
//     "animatronic",
//     "senator",
//     "reality star",
//     "comedian",
//     "frenchman",
//     "sailor",
//     "fighter pilot",
//     "transformer",
//     "lover",
//     "Optimus Prime",
//     "Batman",
//     "prosecutor",
//     "priest",
//     "iron man",
//     "inspector",
//     "dude",
//     "bishop",
//     "pope",
//     "buddha",
//     "predator",
//     "barbarian",
//     "war lord",
//     "Steve Jobs",
//     "eskimo",
//     "scavenger",
//     "model",
//     "super model",
//     "astronaut",
//     "marine",
//     "navy seal",
//     "engineer",
//     "inventor",
//     "scientist",
//     "dentist",
//     "doctor",
//     "mutant",
//     "dummy",
//     "corpse",
//     "author",
//     "fashion designer",
//     "hunter",
//     "bumblebee",
//     "Luke Skywalker",
//     "jedi",
//     "Han Solo",
//     "princess",
//     "prince",
//     "crusader",
//     "parasite",
//     "sith",
//     "smuggler",
//     "narcisist",
//     "whale",
//     "gunner",
//     "mental patient",
//     "prisoner",
//     "inmate",
//     "builder",
//     "detective",
//     "Gordan Ramsay",
//     "Nosferatu",
//     "vlogger",
//     "sith lord",
//     "serpent",
//     "sugar daddy",
//     "roman",
//     "mexican",
//     "nascar driver",
//     "limo driver",
// ];

// var adjectives = [
//     "outworld",
//     "refrigerated",
//     "melting",
//     "origami",
//     "used",
//     "maniac",
//     "captain",
//     "lochness",
//     "successful",
//     "zombie",
//     "genetic",
//     "immortal",
//     "disinfected",
//     "cyber",
//     "undead",
//     "lame",
//     "deaf",
//     "immortal",
//     "paper",
//     "slimy",
//     "pissed off",
//     "delusional",
//     "time",
//     "weather",
//     "sky",
//     "earth",
//     "fire",
//     "invincible",
//     "weird",
//     "night",
//     "smoke",
//     "metal",
//     "unhinged",
//     "super",
//     "invisible",
//     "dead",
//     "smelly",
//     "glass",
//     "sleepy",
//     "horny",
//     "hot",
//     "terrifying",
//     "insane",
//     "useless",
//     "bulimic",
//     "on fire",
//     "old",
//     "brutal",
//     "kinky",
//     "oiled-up",
//     "sexist",
//     "angry",
//     "burnt",
//     "wet",
//     "screaming",
//     "powerful",
//     "vengeful",
//     "unrelenting",
//     "hungry",
//     "short",
//     "disgusting",
//     "robotic",
//     "retarded",
//     "stupid",
//     "handicapped",
//     "mentally-challenged",
//     "young",
//     "inexperienced",
//     "experienced",
//     "creepy",
//     "yodeling",
//     "clown",
//     "flaming",
//     "hypersonic",
//     "frozen",
//     "cold",
//     "improvised",
//     "stuffed",
//     "telekinetic",
//     "made in china",
//     "mutant",
//     "mutated",
//     "nuclear",
//     "autistic",
//     "obese",
//     "fat",
//     "fierce",
//     "deadly",
//     "laser",
//     "bald",
//     "neutron",
//     "mecha",
//     "mega",
//     "infected",
//     "colossal",
//     "female",
//     "male",
//     "fast",
//     "crazy",
//     "smoking",
//     "broken",
//     "exploding",
//     "unreliable",
//     "shot-up",
//     "lead",
//     "steel",
//     "gold",
//     "platinum",
//     "rusty",
//     "collapsing",
//     "broken-down",
//     "exploded",
//     "dying",
//     "brave",
//     "lava",
//     "sex-addicted",
//     "giant",
//     "poisoned",
//     "frost",
//     "schizophrenic",
//     "cursed",
//     "genius",
//     "enchanted",
//     "bloody",
//     "crusty",
//     "blind",
//     "furry",
//     "furious",
//     "duct taped",
//     "glued-together",
//     "cheap",
//     "dollar store",
//     "diamond",
//     "wolverine",
//     "resurrected",
//     "rocket",
//     "pirate",
//     "stolen",
//     "electric",
//     "flying",
//     "depressed",
//     "homeless",
//     "ugly",
//     "plastic",
//     "wooden",
//     "ice",
//     "muscular",
//     "metallic",
//     "sexy",
//     "burning",
//     "relentless",
//     "athletic",
//     "salty",
//     "crying",
//     "affectionate",
//     "ceramic",
//     "ultimate",
//     "supreme",
//     "deluxe",
//     "blazing",
//     "comedic",
//     "unfunny",
//     "clever",
//     "cunning",
//     "crafty",
//     "classy",
//     "shiny",
//     "daring",
//     "determined",
//     "dreamy",
//     "eccentric",
//     "fabulous",
//     "bulky",
//     "fuzzy",
//     "ferocious",
//     "fragile",
//     "formidable",
//     "fearless",
//     "gargantuan",
//     "glorious",
//     "glittery",
//     "groovy",
//     "grizzled",
//     "grumpy",
//     "gleeful",
//     "graceful",
//     "gigantic",
//     "affectionate",
//     "gorgeous",
//     "glistening",
//     "gruesome",
//     "godly",
//     "godlike",
//     "generous",
//     "heroic",
//     "hunky",
//     "handsome",
//     "haunting",
//     "ingenious",
//     "intense",
//     "jazzy",
//     "jiggly",
//     "kooky",
//     "lunar",
//     "logical",
//     "laughable",
//     "magic",
//     "marvelous",
//     "majestic",
//     "monstrous",
//     "mechanical",
//     "nifty",
//     "obnoxious",
//     "organic",
//     "optimal",
//     "proud",
//     "passionate",
//     "quantum",
//     "quirky",
//     "liquid",
//     "radiant",
//     "reckless",
//     "rebellious",
//     "radical",
//     "romantic",
//     "sparkling",
//     "swift",
//     "stylish",
//     "tidal",
//     "transparent",
//     "unstoppable",
//     "unyielding",
//     "unusual",
//     "wacky",
//     "wiggly",
//     "wild",
//     "yummylicious",
//     "youthful",
//     "zealous",
//     "zesty",
//     "gay",
//     "straight",
//     "mental",
//     "shattered",
//     "supersonic",
//     "slippery",
//     "force",
//     "gravity",
//     "granite",
//     "rock",
//     "dirt",
//     "dirty",
//     "tinfoil",
//     "fruity",
//     "naked",
//     "animatronic",
//     "animalistic",
//     "decaying",
//     "vampiric",
//     "shadow",
//     "alien",
//     "chocolate",
//     "wealthy",
//     "billionaire",
//     "millionare",
//     "were",
//     "broke",
//     "poor",
//     "strong",
//     "cotton",
//     "carbon",
//     "lying",
//     "speed",
//     "mad",
//     "cult",
//     "thunder",
//     "kung-fu",
//     "karate",
//     "samurai",
//     "ninja",
//     "barbaric",
//     "microscopic",
//     "toy",
//     "galaxy",
//     "toxic",
//     "sick",
//     "cardboard",
//     "nebula",
//     "death",
//     "drug-addicted",
//     "narcissistic",
//     "polished",
//     "crocheted",
//     "disappointing",
//     "golden",
//     "asteroid",
//     "rat",
//     "possessed",
//     "thunderous",
//     "supermassive",
//     "stealth",
//     "stealthy",
//     "tornado",
//     "blood-sucking",
//     "ancient",
//     "carbon-fiber",
//     "amazing",
// ];

//verbs

// var verbs = [
//     "kill",
//     "destroy",
//     "invade",
//     "pulverize",
//     "disintegrate",
//     "conquer",
//     "decimate",
//     "impregnate",
//     "make love to",
//     "spy on",
//     "summon",
//     "control",
//     "re-animate",
//     "teleport",
//     "pee on",
//     "brutalize",
//     "abuse",
//     "cook",
//     "hire",
//     "kiss",
//     "lick",
//     "spit on",
//     "fight",
//     "infiltrate",
//     "kick",
//     "massage",
//     "punch",
//     "convert",
//     "reverse",
//     "resurrect",
//     "eat",
//     "absorb",
//     "build",
//     "create",
//     "invent",
//     "climb",
//     "vaporize",
//     "sell",
//     "buy",
//     "break",
//     "crush",
//     "re-build",
//     "burn",
//     "freeze",
//     "shoot up",
//     "help",
//     "vote for",
//     "become president of",
//     "become leader of",
//     "become king of",
//     "be a slave to",
//     "lead",
//     "die in",
//     "lose your virginity in",
//     "respawn in",
//     "travel to",
//     "lose to",
//     "steal",
//     "defeat",
//     "banish",
//     "get killed by",
//     "stop",
//     "commit crimes in",
//     "blow up",
//     "rob",
//     "rule",
//     "spend the night with",
//     "break up with",
//     "end",
//     "mutilate",
//     "dominate",
//     "launch",
//     "found",
//     "invest in",
//     "bankrupt",
//     "escape",
//     "flip",
//     "educate",
//     "hose-down",
//     "mail",
//     "ship",
//     "knock out",
//     "work for",
//     "ride",
//     "slap",
//     "smack",
//     "annoy",
//     "anger",
//     "pollute",
//     "fry",
//     "deep-fry",
//     "redeem",
//     "sing to",
//     "bring back",
//     "air-fry",
//     "drown",
//     "terrorize",
//     "liquify",
//     "vacuum",
//     "disinfect",
//     "elect",
//     "manipulate",
//     "inprison",
//     "jail",
//     "arrest",
//     "capture",
//     "corrupt",
//     "seduce",
//     "starve",
//     "get dominated by",
//     "serve",
//     "throw up",
//     "get jiggy with",
//     "be creepy in",
//     "dance in",
//     "regenerate",
//     "subjugate",
//     "become",
//     "understand",
//     "consume",
//     "attack",
//     "blast",
//     "batter",
//     "govern",
//     "harvest",
//     "ignite",
//     "shatter",
//     "inspect",
//     "collapse",
//     "crash",
//     "mystify",
//     "scorch",
//     "scan",
//     "smash",
//     "smite",
//     "strike",
//     "uncover",
//     "wreck",
//     "wrestle",
//     "revolutionize",
//     "engulf",
//     "download",
//     "poison",
//     "reveal",
//     "supercharge",
//     "jump over",
//     "command",
//     "paint",
//     "deceive",
//     "cleanup",
//     "plague",
//     "debate",
//     "argue with",
//     "yell at",
//     "learn about",
//     "combat",
//     "sympathize with",
//     "marry",
//     "shrink",
//     "low-ball",
//     "re-size",
//     "join forces with",
//     "organize",
//     "re-organize",
//     "abolish",
//     "melt",
//     "fire",
//     "be weird to",
//     "be weird about",
//     "be creepy to",
//     "insult",
//     "be mean to",
//     "declare war on",
//     "campaign for",
//     "come out to",
//     "lose your virginity to",
//     "take over",
// ];

// var weapons = [
//     "axe",
//     "lightsaber",
//     "sword",
//     "spear",
//     "ray gun",
//     "nuclear bomb",
//     "bomb",
//     "rifle",
//     "pistol",
//     "wand",
//     "tank",
//     "shoes",
//     "video tape",
//     "bow",
//     "dart gun",
//     "sleigh",
//     "catapult",
//     "trojan horse",
//     "helicopter",
//     "disc",
//     "frisbee",
//     "grenade",
//     "night-vision",
//     "goggles",
//     "trident",
//     "baskbetball",
//     "cat",
//     "knife",
//     "machete",
//     "chainsaw",
//     "soap",
//     "poison",
//     "venom",
//     "dildo",
//     "rocket launcher",
//     "land mine",
//     "crow bar",
//     "pencil",
//     "crock pot",
//     "brick",
//     "bottle",
//     "hair",
//     "hairdryer",
//     "fire axe",
//     "iphone",
//     "jet",
//     "missile",
//     "boulder",
//     "laser",
//     "wall",
//     "fireball",
//     "spray bottle",
//     "ninja star",
//     "shuriken",
//     "fork",
//     "saw",
//     "launcher",
//     "spell book",
//     "paperclip",
//     "gauntlet",
//     "portal gun",
//     "sling shot",
//     "glock",
//     "desert eagle",
//     "stick",
//     "death star",
//     "claws",
//     "knuckles",
//     "bow and arrow",
//     "crossbow",
//     "grappling hook",
//     "spatula",
//     "scissors",
//     "piano",
//     "guitar",
//     "violin",
//     "vape",
//     "cigarette",
//     "baseball bat",
//     "RPG",
//     "hockey stick",
//     "tooth brush",
//     "smoke bomb",
//     "fire ball",
//     "battering ram",
//     "guillotine",
//     "sky beam",
//     "chemicals",
//     "toaster",
//     "oven mitt",
//     "magic",
//     "staff",
//     "shrink ray",
//     "freeze ray",
//     "death ray",
//     "pickaxe",
//     "shovel",
//     "hoe",
//     "wings",
//     "javelin",
// ];

// var locationsAndPlurals = [
//     "Atlantis",
//     "Alabama",
//     "Ugly people",
//     "rodents",
//     "the World",
//     "The Universe",
//     "Helicopters",
//     "Valhala",
//     "Heaven",
//     "Oceans",
//     "Vampires",
//     "Elves",
//     "Werewolves",
//     "Argentina",
//     "fat people",
//     "feminists",
//     "stupid people",
//     "gay people",
//     "straight people",
//     "Viltrum",
//     "Krypton",
//     "Mars",
//     "Uranus",
//     "The Sun",
//     "Jupiter",
//     "Saturn",
//     "Pluto",
//     "Neptune",
//     "Racists",
//     "Mercury",
//     "Venus",
//     "chickens",
//     "giraffes",
//     "serial killers",
//     "cows",
//     "countries",
//     "protestors",
//     "gamers",
//     "Olympus",
//     "cancer patients",
//     "the outworld",
//     "the nether realm",
//     "tilted towers",
//     "time",
//     "dead people",
//     "gingers",
//     "short people",
//     "children",
//     "space",
//     "The Empire State Building",
//     "China",
//     "Russia",
//     "Disney Land",
//     "The 4th Dimension",
//     "other dimensions",
//     "aliens",
//     "cats",
//     "ducks",
//     "the moon",
//     "single moms",
//     "autistic people",
//     "autistic children",
//     "wrestlers",
//     "planets",
//     "horses",
//     "the death star",
//     "mt. Everest",
//     "the twin towers",
//     "babies",
//     "technology",
//     "homeless people",
//     "rocks",
//     "The C.I.A",
//     "France",
//     "french people",
//     "volcanoes",
//     "the earth's core",
//     "cops",
//     "ancient aliens",
//     "greece",
//     "yoga instructors",
//     "the justice league",
//     "the avengers",
//     "the I.R.S",
//     "the F.B.I",
//     "hobbits",
//     "dwarves",
//     "furries",
//     "tax audits",
//     "attractive people",
//     "schools",
//     "the army",
//     "the navy",
//     "the coast guard",
//     "the marines",
//     "the death star",
//     "the white house",
//     "video games",
//     "time machines",
//     "accountants",
//     "wall street",
//     "trees",
//     "musicians",
//     "transformers",
//     "zombies",
//     "criminals",
//     "vampires",
//     "werewolves",
//     "lawyers",
//     "politicians",
//     "salesmen",
//     "influencers",
//     "youtubers",
//     "McDonald's",
//     "Wendy's",
//     "Carl's Jr.",
//     "In N' Out",
//     "Olive Garden",
//     "Chipotle",
//     "the DMV",
//     "Texas",
//     "Germany",
//     "Nebraska",
//     "Rhode Island",
//     "Walmart",
//     "the rainforest",
//     "Pizza Hut",
//     "congress",
//     "the senate",
//     "the mafia",
//     "the mob",
//     "call centers",
//     "the NSA",
//     "planets",
//     "the solar system",
//     "the galaxy",
//     "hospitals",
//     "sick people",
//     "poor people",
//     "the chinese",
//     "the jedi",
//     "the dark side",
//     "sexists",
//     "black holes",
//     "prison",
//     "prisons",
//     "the elderly",
//     "the ice caps",
//     "Antarctica",
//     "Poland",
//     "Alaska",
//     "California",
//     "New York",
//     "New York City",
//     "the asteroid belt",
//     "the pyramids",
//     "Egypt",
//     "The Nile",
//     "Niagra Falls",
//     "Tokyo",
//     "The Desert",
//     "Africa",
//     "Europe",
//     "South America",
//     "Mexico",
//     "Mexicans",
//     "Asians",
//     "white people",
//     "nuclear weapons",
//     "a time machine",
//     "a grape",
//     "the Atlantic Ocean",
//     "the Pacific Ocean",
//     "India",
//     "Japan",
//     "The British",
//     "Middle-Earth",
//     "Tatooine",
//     "Hogwarts",
//     "the land",
//     "the future",
//     "the past",
//     "Mordor",
//     "the death star",
//     "Naboo",
//     "vloggers",
//     "the empire",
//     "empires",
//     "the statue of liberty",
//     "money",
//     "fort knox",
//     "mummies",
//     "the olympics",
//     "the olympic swim team",
//     "communism",
//     "capitalism",
// ];

//abilities

// var abilities = [
//     "beauty",
//     "bravery",
//     "brilliance",
//     "brutality",
//     "calmness",
//     "charity",
//     "coldness",
//     "compassion",
//     "confidence",
//     "courage",
//     "curiosity",
//     "determination",
//     "ego",
//     "elegance",
//     "enthusiasm",
//     "envy",
//     "evil",
//     "faithfulness",
//     "fear",
//     "generosity",
//     "goodness",
//     "hatred",
//     "helpfulness",
//     "honesty",
//     "hope",
//     "humility",
//     "humor",
//     "infatuation",
//     "insanity",
//     "integrity",
//     "intelligence",
//     "jealousy",
//     "kindness",
//     "love",
//     "loyalty",
//     "maturity",
//     "patience",
//     "perseverance",
//     "power",
//     "sanity",
//     "self-control",
//     "sensitivity",
//     "sophistication",
//     "strength",
//     "stupidity",
//     "sympathy",
//     "talent",
//     "tolerance",
//     "trust",
//     "weakness",
//     "wisdom",
//     "wit",
//     "destruction",
//     "speed",
//     "jump",
//     "killing",
//     "reversing",
//     "dancing",
//     "singing",
//     "screaming",
//     "flying",
//     "vision",
//     "lightning",
//     "exploding",
//     "crying",
//     "running",
//     "swimming",
//     "telekinesis",
//     "levitation",
//     "shout",
//     "manipulation",
//     "invisibility",
//     "teleportation",
//     "force fields",
//     "mind control",
//     "control",
//     "blast",
//     "rizz",
//     "seduction",
//     "respawn",
//     "location",
//     "resurrection",
//     "claws",
//     "eyes",
//     "summoning",
//     "burning",
//     "hair",
//     "arms",
//     "arm",
//     "legs",
//     "leg",
//     "body",
//     "head",
//     "shape-shifting",
//     "shaming",
//     "electricity",
//     "chemistry",
//     "chemicals",
//     "hands",
//     "thumb",
//     "bending",
//     "levitating",
//     "spinning",
//     "projection",
//     "lifting",
//     "throwing",
//     "backflip",
//     "stabbing",
//     "gravity",
//     "magnetism",
//     "transforming",
//     "speaking",
//     "magic",
//     "black magic",
//     "melting",
//     "smell",
//     "regeneration",
//     "bolt",
//     "punch",
//     "slap",
//     "kick",
//     "drop kick",
//     "uppercut",
//     "roundhouse kick",
//     "karate chop",
//     "plague",
//     "laugh",
//     "thunder",
//     "storm",
//     "locating",
//     "echolocation",
//     "headbutt",
//     "disappearing",
//     "vanishing",
//     "stealth",
//     "tornado",
// ];

//vehicles

// var vehicles = [
//     "car",
//     "bus",
//     "bike",
//     "airplane",
//     "trash can",
//     "bat-mobile",
//     "jet",
//     "hot air balloon",
//     "truck",
//     "shoes",
//     "rollerblades",
//     "hoverboard",
//     "cannon",
//     "hang glider",
//     "teleporter",
//     "space-ship",
//     "speeder",
//     "clown car",
//     "scooter",
//     "tricycle",
//     "motorcycle",
//     "boat",
//     "skiis",
//     "snowboard",
//     "canoe",
//     "zipline",
//     "ice skates",
//     "carriage",
//     "horse",
//     "sled",
//     "helicopter",
//     "semi truck",
//     "race car",
//     "blimp",
//     "tank",
//     "hamster ball",
//     "tardis",
//     "millennium falcon",
//     "U.S.S Enterprise",
//     "Star Destroyer",
//     "space shuttle",
//     "rocket ship",
//     "pirate ship",
//     "slip n' slide",
//     "row boat",
//     "ostrich",
//     "t-rex",
//     "chevy",
//     "ford",
//     "toyota",
//     "tesla",
//     "moped",
//     "four-wheeler",
// ];

//firstnames

var firstNames = [
    "Steve",
    "Bob",
    "Will",
    "Mary-Sue",
    "Philip",
    "Peter",
    "Lebron",
    "Arnold",
    "Donald",
    "liu",
    "Walter",
    "Jesse",
    "Santa",
    "Boo-boo",
    "Honey",
    "Michael",
    "Dingster",
    "Wobby",
    "Flapbag",
    "Flapjack",
    "Marco",
    "Mario",
    "Gobsmack",
    "Nick",
    "Ballsac",
    "Lord",
    "King",
    "Cumquat",
    "Dillsack",
    "Margot",
    "Dr.",
    "Mr.",
    "Joseph",
    "Tony",
    "GoatSucker",
    "RatHumper",
    "NipTwister",
    "Coolio",
    "Steve",
    "Focker",
    "James",
    "Kent",
    "Hooboo",
    "Boo-boo",
    "Robbie",
    "Jackson",
    "Jackoff",
    "Wigglekins",
    "Gillington",
    "McGee",
    "Retardo",
    "ButtBottom",
    "HoboHumper",
    "Nimrod",
    "LimpDick",
    "beyonce",
    "Booberton",
    "Dick-wad",
    "Dillweed",
    "Dill-wad",
    "Dicker",
    "Jesus",
    "Vladimir",
    "Dingbat",
    "Captain",
    "Ted",
    "Jezanthepuss",
    "Willington",
];

var lastNames = [
    "Parker",
    "Bin-Laden",
    "White",
    "Mercury",
    "Hitler",
    "Stalin",
    "Griffin",
    "Simpson",
    "Schwarzenegger",
    "Cruise",
    "Stark",
    "Kenobi",
    "Skywalker",
    "Travolta",
    "Arthur",
    "Vader",
    "Obama",
    "Bush",
    "Clinton",
    "Reagan",
    "Washington",
    "Lincoln",
    "Smith",
    "Banner",
    "Musk",
    "Hawking",
    "Hemsworth",
    "Dafoe",
    "Bieber",
    "Christ",
    "Clause",
    "James",
    "Jordan",
    "Jackson",
    "Goodman",
    "Trump",
    "Cage",
    "Putin",
    "Dracula",
    "Hogan",
    "Rock",
    "Edison",
    "Tesla",
    "Wayne",
    "Manson",
    "Lennon",
    "Winfrey",
    "BooBoo",
    "America",
    "Bundy",
];

var fullNames = [
    "Peter Parker",
    "Osama Bin-Laden",
    "Walter White",
    "Freddie Mercury",
    "Adolf Hitler",
    "Joseph Stalin",
    "Peter Griffin",
    "Homer Simpson",
    "Arnold Schwarzenegger",
    "Tom Cruise",
    "Tony Stark",
    "Obi-Wan Kenobi",
    "Luke Skywalker",
    "John Travolta",
    "King Arthur",
    "Darth Vader",
    "Barack Obama",
    "George Bush",
    "Bill Clinton",
    "Ronald Reagan",
    "George Washington",
    "Abraham Lincoln",
    "Will Smith",
    "Bruce Banner",
    "Elon Musk",
    "Stephen Hawking",
    "Chris Hemsworth",
    "Willem Dafoe",
    "Justin Bieber",
    "Jesus Christ",
    "Santa Clause",
    "Lebron James",
    "Michael Jordan",
    "Michael Jackson",
    "Saul Goodman",
    "Donald Trump",
    "Nicolas Cage",
    "Vladimir Putin",
    "Count Dracula",
    "Hulk Hogan",
    "The Rock",
    "Thomas Edison",
    "Nicola Tesla",
    "John Wayne",
    "Charles Manson",
    "John Lennon",
    "Oprah Winfrey",
    "Honey BooBoo",
    "Captain America",
    "Ted Bundy",
];